### ISSUE TITLE
Feature Request: Add ability to convert TEXT to HEX to add in messages to transactions

### ISSUE THREAD

**Issue by patoshii** [m2049r/xmrwallet#171] opened 2017-12-27 22:18 UTC
the payment id field can take upto 64 hex characters. it would be great if we can attach a message to each transaction that translates back into plain text. 

- add new message field
- auto converts text to hex with max limit of 64 hex characters.

**Comment by jenniferberger** [comment] 2018-04-23 19:52
duplicate of #130

**Closed as completed** 2018-04-30 19:50 UTC
Labels: duplicate
