### ISSUE TITLE
Automatic Wallet Fee

### ISSUE THREAD

**Issue by juanpc2018** [m2049r/xmrwallet#210] opened 2018-03-19 01:35 UTC
monerujo has the same problem as btc.com web wallet.

there is No automatic substraction fee.!
for example: if i have multiple small wallets, and want to send all to a single wallet, or someone has a small amount and want to pay me for something.
monerujo does not automaticallty substract the fee from the amount.!
gives an error:

**Create Transaction Error**
not enough money to transfer,
available only 0.xxxxxxx
transaction amount
0.xx258609xxx =
0.xxxxxxxxxxx +
0.002586090000 (fee)

to send i have to manually open the calculator.
and guess the fee! to empty the wallet.!
That is Crazy.!

**Comment by m2049r** [comment] 2018-03-21 21:47
the fee is only known AFTER the transactions is constructed. so what you are asking is impossible. UNLESS you want to send everything - this is a function on the backlog (sweep_all).

**Comment by jonathancross** [comment] 2018-05-04 08:27
Seems this is a duplicate of the "sweep all" feature request? https://github.com/m2049r/xmrwallet/issues/213

**Comment by m2049r** [comment] 2018-05-12 07:41
let's say it is, as the fee cannot be calculated either way.

**Closed as completed by m2049r** 2018-05-12 07:41 UTC
Labels: duplicate
